services:
 - type: web
   name: nextjs-static
   runtime: static
   buildCommand: npm i; npm run build
   staticPublishPath: out
#   pullRequestPreviewsEnabled: true     # optional
#   envVars:
#   - key: NODE_ENV
#     value: production